input {
  generator {
    count => 500000
    message => "benchmarkdata"
    add_field => {
      "field1" => "alpha"
      "field2" => "beta"
      "field3" => "gamma"
      "field4" => "delta"
      "field5" => "epsilon"
      "field6" => "zeta"
      "field7" => "eta"
      "field8" => "theta"
    }
  }
}

output {
  csv {
    path => "${LS_BENCH_OUTPUT}"
    fields => ["message","field1","field2","field3","field4","field5","field6","field7","field8","@timestamp"]
  }
}
